[gsheets]
curri_url = "https://docs.google.com/spreadsheets/d/1GD6C-mIThAYfMm10VmO6S79ZkWdbsOZrudXEcwfIfzA/edit?usp=sharing"
idea_url = "https://docs.google.com/spreadsheets/d/1GD6C-mIThAYfMm10VmO6S79ZkWdbsOZrudXEcwfIfzA/edit?gid=668830004#gid=668830004"